[package]
name = "tser_codegen"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tser_ir = { path = "../tser_ir" }
tser_block = { path = "../tser_block" }
convert_case = "0.6"
#bytestring = "1.1.0"
